# Generated by Django 3.0.6 on 2020-06-29 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleCate', models.CharField(max_length=100)),
                ('etatC', models.BooleanField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=100)),
                ('prenomClient', models.CharField(max_length=100)),
                ('numeroClient', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateFacture', models.DateField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Facture_Ligne',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefac', models.DateField(auto_now=True)),
                ('qteAchete', models.IntegerField(default=None)),
                ('gain', models.FloatField(default=None)),
                ('factureId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Facture')),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomF', models.CharField(max_length=100)),
                ('prenomF', models.CharField(max_length=100)),
                ('adresseF', models.CharField(max_length=50)),
                ('telephone', models.IntegerField(default=None)),
                ('mail', models.EmailField(default=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateField(auto_now=True)),
                ('remise', models.FloatField(default=None)),
                ('totalPaye', models.FloatField(default=None)),
                ('totalFactur', models.FloatField(default=None)),
                ('SomRemise', models.FloatField(default=None)),
                ('monnaiRemise', models.FloatField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='TypeUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelle', models.CharField(max_length=100)),
                ('userId', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='statistique',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalgain', models.FloatField(default=None)),
                ('totalvente', models.FloatField(default=None)),
                ('ligneFacture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Facture_Ligne')),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleProd', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(default=None)),
                ('prixAchat', models.FloatField(default=None)),
                ('prixVente', models.FloatField(default=None)),
                ('stock', models.IntegerField(default=None)),
                ('description', models.CharField(max_length=150)),
                ('etatP', models.BooleanField(null=True)),
                ('cateProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categorie')),
                ('fournisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Fournisseur')),
            ],
        ),
        migrations.AddField(
            model_name='facture_ligne',
            name='produitId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit'),
        ),
        migrations.AddField(
            model_name='facture',
            name='venteId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Vente'),
        ),
        migrations.CreateModel(
            name='Entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtE', models.IntegerField(default=None)),
                ('qtAvant', models.IntegerField(default=None)),
                ('dateE', models.DateField(auto_now=True)),
                ('etatE', models.BooleanField(null=True)),
                ('prodE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit')),
            ],
        ),
    ]
