# Generated by Django 3.0.6 on 2020-05-29 15:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleCate', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomClient', models.CharField(max_length=100)),
                ('prenomClient', models.CharField(max_length=100)),
                ('numeroClient', models.IntegerField(default=None)),
            ],
        ),
        migrations.CreateModel(
            name='Fournisseur',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomF', models.CharField(max_length=100)),
                ('prenomF', models.CharField(max_length=100)),
                ('adresseF', models.CharField(max_length=50)),
                ('telephone', models.IntegerField(default=None)),
                ('mail', models.EmailField(default=True, max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Produit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('libelleProd', models.CharField(max_length=100)),
                ('quantite', models.IntegerField(default=None)),
                ('prixAchat', models.IntegerField(default=None)),
                ('prixVente', models.IntegerField(default=None)),
                ('stock', models.IntegerField(default=None)),
                ('description', models.CharField(max_length=150)),
                ('cateProd', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Categorie')),
            ],
        ),
        migrations.CreateModel(
            name='Vente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateVente', models.DateField(null=True)),
                ('clt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Client')),
                ('prod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Sorti',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtS', models.IntegerField(default=None)),
                ('prixS', models.IntegerField(default=None)),
                ('dateS', models.DateField(null=True)),
                ('fourS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Fournisseur')),
                ('prodS', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit')),
            ],
        ),
        migrations.CreateModel(
            name='Entre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qtE', models.IntegerField(default=None)),
                ('dateE', models.DateField(auto_now=True)),
                ('prodE', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shop.Produit')),
            ],
        ),
    ]
