# Generated by Django 3.0.6 on 2020-06-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture_ligne',
            name='prix',
            field=models.FloatField(default=None),
        ),
    ]
