# Generated by Django 3.0.6 on 2020-06-30 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_facture_ligne_prix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='statistique',
            name='ligneFacture',
        ),
        migrations.AddField(
            model_name='statistique',
            name='dateF',
            field=models.DateField(auto_now=True),
        ),
        migrations.AddField(
            model_name='statistique',
            name='facturestat',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='shop.Facture'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='statistique',
            name='totalvente',
            field=models.FloatField(null=True),
        ),
    ]
