# Generated by Django 3.0.6 on 2020-07-02 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_auto_20200630_2242'),
    ]

    operations = [
        migrations.AddField(
            model_name='facture',
            name='totalG',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='facture',
            name='totalV',
            field=models.FloatField(null=True),
        ),
    ]
